#
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${pctol.datasource.driver-class-name}
    url: jdbc:mysql://${pctol.datasource.host}:${pctol.datasource.port}/${pctol.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${pctol.datasource.username}
    password: ${pctol.datasource.password}
#
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#
server:
  port: 8080
