#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practical_online?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Administrator
    driver-class-name: com.mysql.cj.jdbc.Driver
#
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#
server:
  port: 8080